Repository kubeflow/example-seldon, pull requests merged in 2019-05, with the labels that each got.

#37 move to kaniko instead of s2i
  .gitignore
  README.md
  k8s_setup/docker-credentials-secret.yaml.tpl
  models/r_mnist/runtime/.s2i/environment
  models/r_mnist/runtime/Dockerfile
  models/r_mnist/runtime/Makefile
  models/r_mnist/runtime/wrap.sh
  models/r_mnist/train/Dockerfile
  models/r_mnist/train/build_and_push.sh
  models/sk_mnist/runtime/.s2i/environment
  models/sk_mnist/runtime/Dockerfile
  models/sk_mnist/runtime/Makefile
  models/sk_mnist/runtime/requirements.txt
  models/sk_mnist/runtime/wrap.sh
  models/sk_mnist/train/Dockerfile
  models/sk_mnist/train/build_and_push.sh
  models/tf_mnist/runtime/.s2i/environment
  models/tf_mnist/runtime/Dockerfile
  models/tf_mnist/runtime/Makefile
  models/tf_mnist/runtime/requirements.txt
  models/tf_mnist/runtime/wrap.sh
  models/tf_mnist/train/build_and_push.sh
  notebooks/training.ipynb
  scripts/create_demo.sh
  scripts/env-example.sh
  workflows/serving-r-mnist-workflow.yaml
  workflows/serving-sk-mnist-workflow.yaml
  workflows/serving-tf-mnist-workflow.md
  workflows/serving-tf-mnist-workflow.yaml
  workflows/training-r-mnist-workflow.yaml
  workflows/training-sk-mnist-workflow.yaml
  workflows/training-tf-mnist-workflow.md
  workflows/training-tf-mnist-workflow.yaml
Labels: approved, lgtm, size/XL

#40 Add Ryan Dawson to OWNERS file
  OWNERS
Labels: approved, lgtm, size/XS

#41 add jinchihe as approver
  OWNERS
Labels: approved, lgtm, size/XS

#39 Provide notebook pip requirements and default kubeflow version in example env
  README.md
  notebooks/requirements.txt
  scripts/env-example.sh
Labels: approved, lgtm, size/S
