Repository kubeflow/example-seldon, pull requests merged in 2019-02, with the labels that each got.

#23 Fix for Seldon 0.2.5
  k8s_serving/epsilon_greedy.json
  k8s_serving/serving_r_model.json
  k8s_serving/serving_sk_model.json
Labels: needs-ok-to-test, size/S

#24 update README to correct markdown numbered list
  README.md
Labels: lgtm, size/M

#25 update training-tf-mnist-workflow.md to fix bad link
  workflows/training-tf-mnist-workflow.md
Labels: lgtm, size/XS

#26 update namespace for docker_secret file
  k8s_setup/docker-credentials-secret.yaml.tpl
Labels: lgtm, size/XS

#27 update serving-tf-mnist-workflow.md
  workflows/serving-tf-mnist-workflow.md
Labels: lgtm, size/XS

#28 update apiVersion for SeldonDeployment
  workflows/serving-r-mnist-workflow.yaml
  workflows/serving-sk-mnist-workflow.yaml
  workflows/serving-tf-mnist-workflow.yaml
Labels: lgtm, size/XS

#29 update workflow to componentSpecs
  workflows/serving-r-mnist-workflow.yaml
  workflows/serving-sk-mnist-workflow.yaml
  workflows/serving-tf-mnist-workflow.yaml
Labels: lgtm, size/L

#30 update serving.ipynb
  notebooks/serving.ipynb
Labels: lgtm, size/S

#32 update Readme file to fix a bad link
  README.md
Labels: lgtm, size/XS
